"""add relations

Revision ID: 24ea4a610d55
Revises: a288033fad12
Create Date: 2023-08-17 16:23:44.576328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ea4a610d55'
down_revision = 'a288033fad12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("owner_pets", 'owners', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_constraint("owner_pets", type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
